# Definición de la API de Kubernetes para Servicios
apiVersion: v1
kind: Service
metadata:
  # Nombre del servicio que se usará para la resolución de DNS interno
  name: casino-backend
  namespace: default
  labels:
    app: casino-backend
spec:
  # Mapeo de puertos
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  # Selector para encontrar qué pods pertenecen a este servicio
  selector:
    app: casino-backend
  # Tipo de servicio: ClusterIP (solo accesible internamente en el clúster)
  type: ClusterIP
